packages:
  - workflow
  - model
  - ui
  - test
  - block

catalog:
  "@platforma-sdk/model": 1.42.51
  "@platforma-sdk/ui-vue": 1.42.51
  "@platforma-sdk/workflow-tengo": 5.1.4
  "@platforma-sdk/block-tools": 2.6.2
  "@platforma-sdk/test": 1.42.52
  "@platforma-sdk/tengo-builder": 2.1.18
  "@platforma-sdk/package-builder": 3.2.4
  "@platforma-sdk/eslint-config": ^1.1.0
  "@platforma-sdk/blocks-deps-updater": ^2.0.0

  "@platforma-open/milaboratories.runenv-python-3": ^1.1.16
  
  "vue": ^3.5.15
  "vue-tsc": ^2.2.10
  
  "typescript": ~5.5.4
  "turbo": ^2.5.6

  "vite": ^6.3.5
  "vitest": ~2.1.9
  "@vitejs/plugin-vue": ^5.2.4
  "vite-plugin-dts": ^4.3.0

  "@changesets/cli": ^2.29.6
