packages:
  - workflow
  - model
  - ui
  - test
  - block

catalog:
  "@platforma-sdk/model": 1.58.5
  "@platforma-sdk/ui-vue": 1.58.8
  "@platforma-sdk/workflow-tengo": 5.9.0
  "@platforma-sdk/block-tools": 2.6.63
  "@platforma-sdk/test": 1.58.7
  "@platforma-sdk/tengo-builder": 2.4.25
  "@platforma-sdk/package-builder": ^3.11.4
  "@platforma-sdk/eslint-config": ^1.2.0
  "@platforma-sdk/blocks-deps-updater": ^2.0.1

  "vue": ^3.5.24
  "vue-tsc": ^2.2.10
  
  "typescript": ~5.6.3
  "turbo": ^2.5.8

  "vite": ^6.3.5
  "vitest": ~4.0.18
  "@vitejs/plugin-vue": ^5.2.4
  "vite-plugin-dts": ^4.3.0
  'shx': ^0.4.0

  "@changesets/cli": ^2.29.6
