packages:
  - workflow
  - model
  - ui
  - test
  - software
  - block

catalog:
  "@platforma-sdk/model": ^1.41.6
  "@platforma-sdk/ui-vue": ^1.41.6
  "@platforma-sdk/workflow-tengo": ^4.13.0
  "@platforma-sdk/block-tools": ^2.5.71
  "@platforma-sdk/test": ^1.41.8
  "@platforma-sdk/tengo-builder": ^2.1.12
  "@platforma-sdk/package-builder": ^2.16.2
  "@platforma-sdk/eslint-config": ^1.0.3

  "@platforma-open/milaboratories.runenv-python-3": ^1.1.7
  
  "vue": ^3.5.15
  "vue-tsc": ^2.2.10
  
  "typescript": ~5.5.4
  "turbo": ^2.5.4

  "vite": ^6.3.5
  "vitest": ~2.1.9
  "@vitejs/plugin-vue": ^5.2.4
  "vite-plugin-dts": ^4.3.0

  "@changesets/cli": ^2.29.5
  "js-yaml": "^4.1.0"
