packages:
  - workflow
  - model
  - ui
  - test
  - software
  - block

catalog:
  "@platforma-sdk/model": 1.42.25
  "@platforma-sdk/ui-vue": 1.42.26
  "@platforma-sdk/workflow-tengo": ^5.0.3
  "@platforma-sdk/block-tools": ^2.5.83
  "@platforma-sdk/test": 1.42.27
  "@platforma-sdk/tengo-builder": 2.1.16
  "@platforma-sdk/package-builder": 2.17.2
  "@platforma-sdk/eslint-config": ^1.0.3

  "@platforma-open/milaboratories.runenv-python-3": ^1.1.16
  
  "vue": ^3.5.15
  "vue-tsc": ^2.2.10
  
  "typescript": ~5.5.4
  "turbo": ^2.5.6

  "vite": ^6.3.5
  "vitest": ~2.1.9
  "@vitejs/plugin-vue": ^5.2.4
  "vite-plugin-dts": ^4.3.0

  "@changesets/cli": ^2.29.6
  "js-yaml": "^4.1.0"
