packages:
  - workflow
  - model
  - ui
  - test
  - block

catalog:
  "@platforma-sdk/model": 1.53.2
  "@platforma-sdk/ui-vue": 1.53.2
  "@platforma-sdk/workflow-tengo": 5.8.1
  "@platforma-sdk/block-tools": 2.6.35
  "@platforma-sdk/test": 1.53.2
  "@platforma-sdk/tengo-builder": 2.4.12
  "@platforma-sdk/package-builder": ^3.10.7
  "@platforma-sdk/eslint-config": ^1.2.0
  "@platforma-sdk/blocks-deps-updater": ^2.0.0

  "vue": ^3.5.24
  "vue-tsc": ^2.2.10
  
  "typescript": ~5.6.3
  "turbo": ^2.5.8

  "vite": ^6.3.5
  "vitest": ~2.1.9
  "@vitejs/plugin-vue": ^5.2.4
  "vite-plugin-dts": ^4.3.0
  'shx': ^0.4.0

  "@changesets/cli": ^2.29.6
